version: '2'

services:
    celery_worker:
        build: .
        command: "celery -A tasks worker --loglevel INFO"
    celery_beat_scheduler:
        build: .
        command: "celery -A tasks beat --loglevel DEBUG"
    redis:
        image: "redis:3"
